### ISSUE TITLE
node_modules for real?

### ISSUE THREAD

**Issue by chenyong** [actions/hello-world-javascript-action#12]
I see `node_modules/` included in the project while it's considered bad practice to have it in git repo. Is is the only way to make sure Node runs well in actions with correct dependencies? Can I install the packages during(or before) action is really running?

**Comment by 123aswin123** [comment]
@chenyong I agree with you 100%



 However, here is a workaround if node_modules is in your gitignore and you wish to generate node_modules during runtime:

```yml

on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]
    name: A job to say hello
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Packages
        run: npm install
      - name: Hello world action step
        uses: ./ # Uses an action in the root directory
        id: hello
        with:
          who-to-greet: "Mona the Octocat!!!!!"
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"


```

The above mentioned code is a remix of the code given [here](https://docs.github.com/en/free-pro-team@latest/actions/creating-actions/creating-a-javascript-action#testing-out-your-action-in-a-workflow)
